name: Node.js CI

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: macos-latest

        strategy:
            matrix:
                node-version: [22.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - run: npm ci
            - run: npm run build --if-present

            # Add the deployment step here
            - name: Deploy to Render
              run: |
                  curl -X POST \
                       -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
                       -H "Content-Type: application/json" \
                       -d '{"service_id": "${{ secrets.SERVICE_ID }}"}' \
                       https://api.render.com/v1/services/${{ secrets.SERVICE_ID }}/deployments
              env:
                  RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
                  SERVICE_ID: ${{ secrets.SERVICE_ID }}
